---
name: Publish a Docker image (ARM64; Apple Silicon)

# yamllint disable-line rule:truthy
on:
  push:
    tags: ["*"]
    branches:
      - ros2
      - dockertest

env:
  IMAGE_NAME: ${{ github.repository }}
  ROS_DISTRO: jazzy
  BRANCH: ros2

jobs:
  build-and-push-to-docker-hub:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 1440
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ioeslab/dave
          tags: ros2-arm-rdp

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: .docker/jazzy.arm64v8.dockerfile
          platforms: linux/arm64/v8
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            BRANCH=${{ env.BRANCH }}

      - name: Debug environment variables
        run: |
          echo "ROS_DISTRO: ${ROS_DISTRO}"
          echo "BRANCH: ${BRANCH}"
